swagger: '2.0'
info:
  description: Balanced Jobs App
  title: balanced-jobs-app
  version: 1.0.0
basePath: /api/v1
paths:
  /new-offer:
    post:
      parameters: []
      responses:
        '200':
          description: return the new offer id
      tags:
        - Jobs
      description: creates a new offer
  '/offer/{offerId}':
    delete:
      parameters:
        - in: path
          name: offerId
          required: true
          type: string
          x-example: 5a3eb620260b8700140e500e
      responses:
        '200':
          description: Returns all offers
      tags:
        - Jobs
      description: Deletes an offer
    get:
      parameters:
        - in: path
          name: offerId
          required: true
          type: string
          x-example: 5a3eb620260b8700140e500e
      responses:
        '200':
          description: Returns the offer with id offerId
      tags:
        - Jobs
      description: Returns the offer with id offerId
    patch:
      consumes:
        - application/json
      parameters:
        - in: path
          name: offerId
          required: true
          type: string
          x-example: 5a3eb620260b8700140e500e
        - description: the ISerieUpdate data
          in: body
          name: body
          required: true
          schema:
            description: The updated object
            type: object
      responses:
        '200':
          description: Returns the offer with id offerId
      tags:
        - Jobs
      description: Updates the offer
  /offers:
    get:
      parameters: []
      responses:
        '200':
          description: Returns all offers
      tags:
        - Jobs
      description: Fetch all offers
  /spec:
    get:
      parameters: []
      responses:
        '200':
          description: Return the API specification
      tags:
        - Specification
tags:
  - name: Jobs

